CREATING AN 1-D ARRAY IN NUMPY 

In [4]:
import numpy as np

x = [1,2,3,4,5,6]

y = np.array(x)

print(y)

CREATING AN ARRAY OF USER INPUT 

In [7]:
import numpy as np 
l = []
for i in range(1,5):
    inp = int(input("insert no. in array : "))
    l.append(inp)
print(np.array(l))

[ 1  2 23 54]


CREATING A 2-D ARRAY      (both the arrays have same no. of elements otherwise it will be inhomogeneous array/ matrix)     

In [8]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[1,2,3,5]])

print(arr_2d)


[[1 2 3 4]
 [1 2 3 5]]


using "ndim" to check the dimensions of an array 

In [10]:
y = (arr_2d.ndim)
print(y)

2


CREATING A 3-D ARRAY 

In [4]:
import numpy as np
arr_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


to create a 'n' dimension array we can use "ndmin = _value_"

In [7]:
import numpy as np
arrn =  np.array([1,2,3,4],ndmin = 10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
