 # CREATING AN ARRAY WITH ALL ZERO ELEMENTS 

In [6]:
import numpy as np 

arr = np.zeros(3)
arr1 = np.zeros((3,4))
print(arr)
print()
print(arr1)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


 # With all ones

In [11]:
import numpy as np
arr2 = np.ones(3)
arr3= np.ones((3,3))
print(arr3)
print()
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[1. 1. 1.]


 # Empty array 

In [12]:
arr4 = np.empty(4)
print(arr4)

[2.12199579e-314 1.08646184e-311 6.73905541e-321 1.08646185e-311]


# Ranged array

In [13]:
arr5 = np.arange(5)
print(arr5)

[0 1 2 3 4]


# TO create an identity matrix

In [20]:
arr6 = np.eye(6,6)
print(arr6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Generating random values using rand function 

In [26]:
arr_ran1 = np.random.rand(4) #generates random +ve no. btw 0-1
arr_ran = np.random.randn(4) #generates random both +ve and -ve on. btw 0-1
arr_ran2 = np.random.ranf(4) #generates random floats 
arr_ran3 = np.random.randint(0,10,7) #generates random no. btw a give range (min, max ,total no's to print)
print(arr_ran)
print(arr_ran1)
print(arr_ran2)
print(arr_ran3)

[-1.6915122   0.76405611  2.18635605  1.22184399]
[0.79087663 0.35311224 0.36964312 0.11391599]
[0.78359382 0.90748979 0.54274819 0.28945233]
[2 0 8 9 4 1 4]
